"""GET/POST helpers for runtime settings (API keys, model paths)."""

from __future__ import annotations

from typing import Any

from app.config import settings
from app.env_persist import update_env_value
from app.platform_info import normalize_path
from app.secrets import is_blank_or_placeholder, is_secret_field, mask_secret


def public_settings() -> dict[str, Any]:
    """Safe settings for the UI — secrets never returned in cleartext."""
    payload = {
        "model_backend": settings.model_backend,
        "ollama_base_url": settings.ollama_base_url,
        "ollama_model": settings.ollama_model,
        "openai_compat_base_url": settings.openai_compat_base_url,
        "openai_compat_model": settings.openai_compat_model,
        "openai_compat_api_key_set": bool(settings.openai_compat_api_key),
        "openai_compat_api_key_masked": mask_secret(settings.openai_compat_api_key),
        "hermes_base_url": settings.hermes_base_url,
        "hermes_model": settings.hermes_model,
        "hermes_api_key_set": bool(settings.hermes_api_key),
        "hermes_api_key_masked": mask_secret(settings.hermes_api_key),
        "hermes_session_key_set": bool(settings.hermes_session_key),
        "hermes_session_key_masked": mask_secret(settings.hermes_session_key),
        "hermes_show_tool_progress": settings.hermes_show_tool_progress,
        "hf_model": settings.hf_model,
        "hf_token_set": bool(settings.hf_token),
        "hf_token_masked": mask_secret(settings.hf_token),
        "unsloth_model": settings.unsloth_model,
        "unsloth_adapter_dir": settings.unsloth_adapter_dir,
        "unsloth_max_seq_length": settings.unsloth_max_seq_length,
        "unsloth_load_in_4bit": settings.unsloth_load_in_4bit,
        "web_search_enabled": settings.web_search_enabled,
        "web_search_max_results": settings.web_search_max_results,
        "web_search_timeout_sec": settings.web_search_timeout_sec,
        "searxng_url": settings.searxng_url or "",
        "net_assess_enabled": settings.net_assess_enabled,
        "net_assess_use_nmap": settings.net_assess_use_nmap,
        "local_tools_enabled": settings.local_tools_enabled,
        "local_tools_auto": settings.local_tools_auto,
        "local_tools_allow_heavy": settings.local_tools_allow_heavy,
        "zap_api_url": getattr(settings, "zap_api_url", "") or "http://127.0.0.1:8090",
        "zap_api_key_set": bool(getattr(settings, "zap_api_key", "")),
        "zap_prefer_api": bool(getattr(settings, "zap_prefer_api", False)),
        "jira_base_url": settings.jira_base_url or "",
        "jira_email": settings.jira_email or "",
        "jira_project_key": settings.jira_project_key or "",
        "jira_api_token_set": bool(settings.jira_api_token),
        "jira_api_token_masked": mask_secret(settings.jira_api_token),
        "router_enabled": settings.router_enabled,
        "openai_api_key_set": bool(settings.openai_api_key),
        "openai_api_key_masked": mask_secret(settings.openai_api_key),
        "openai_model": settings.openai_model,
        "openrouter_api_key_set": bool(settings.openrouter_api_key),
        "openrouter_api_key_masked": mask_secret(settings.openrouter_api_key),
        "openrouter_model": settings.openrouter_model,
        "groq_api_key_set": bool(settings.groq_api_key),
        "groq_api_key_masked": mask_secret(settings.groq_api_key),
        "groq_model": settings.groq_model,
        "together_api_key_set": bool(settings.together_api_key),
        "together_api_key_masked": mask_secret(settings.together_api_key),
        "together_model": settings.together_model,
        "fireworks_api_key_set": bool(settings.fireworks_api_key),
        "fireworks_api_key_masked": mask_secret(settings.fireworks_api_key),
        "fireworks_model": settings.fireworks_model,
        "huggingface_api_model": settings.huggingface_api_model,
        "ollama_coder_model": settings.ollama_coder_model or "",
        "abuseipdb_api_key_set": bool(settings.abuseipdb_api_key),
        "virustotal_api_key_set": bool(settings.virustotal_api_key),
        "shodan_api_key_set": bool(settings.shodan_api_key),
        "otx_api_key_set": bool(settings.otx_api_key),
        "urlscan_api_key_set": bool(settings.urlscan_api_key),
        "hibp_api_key_set": bool(settings.hibp_api_key),
        "greynoise_api_key_set": bool(settings.greynoise_api_key),
        "pulsedive_api_key_set": bool(settings.pulsedive_api_key),
        "malwarebazaar_api_key_set": bool(settings.malwarebazaar_api_key),
        "emailrep_api_key_set": bool(settings.emailrep_api_key),
        "urlhaus_api_key_set": bool(settings.urlhaus_api_key),
        "github_webhook_secret_set": bool(settings.github_webhook_secret),
        "gitlab_webhook_secret_set": bool(getattr(settings, "gitlab_webhook_secret", "")),
        "taxii_api_root": getattr(settings, "taxii_api_root", "") or "",
        "taxii_collection_id": getattr(settings, "taxii_collection_id", "") or "",
        "taxii_username": getattr(settings, "taxii_username", "") or "",
        "taxii_password_set": bool(getattr(settings, "taxii_password", "")),
        "oidc_enabled": settings.oidc_enabled,
        "oidc_issuer": settings.oidc_issuer or "",
        "oidc_client_id": settings.oidc_client_id or "",
        "oidc_redirect_uri": settings.oidc_redirect_uri or "",
        "oidc_scopes": settings.oidc_scopes or "openid profile email",
        "oidc_client_secret_set": bool(settings.oidc_client_secret),
        "scim_enabled": bool(getattr(settings, "scim_enabled", False)),
        "scim_token_set": bool(getattr(settings, "scim_token", "")),
        "mfa_required_for_admin": settings.mfa_required_for_admin,
        "database_url_set": bool(settings.database_url),
        "redis_url_set": bool(settings.redis_url),
        "prefect_enabled": bool(getattr(settings, "prefect_enabled", False)),
        "prefect_api_url": getattr(settings, "prefect_api_url", "") or "",
        "siem_forward_enabled": bool(getattr(settings, "siem_forward_enabled", False)),
        "siem_forward_url": getattr(settings, "siem_forward_url", "") or "",
        "siem_hec_token_set": bool(getattr(settings, "siem_hec_token", "")),
        "siem_syslog_host": getattr(settings, "siem_syslog_host", "") or "",
        "siem_syslog_port": int(getattr(settings, "siem_syslog_port", 514) or 514),
        "siem_azure_sentinel_enabled": bool(getattr(settings, "siem_azure_sentinel_enabled", False)),
        "siem_azure_dce_url": getattr(settings, "siem_azure_dce_url", "") or "",
        "siem_azure_dcr_immutable_id": getattr(settings, "siem_azure_dcr_immutable_id", "") or "",
        "siem_azure_stream_name": getattr(settings, "siem_azure_stream_name", "") or "Custom-SecuraIQEvents_CL",
        "siem_azure_tenant_id": getattr(settings, "siem_azure_tenant_id", "") or "",
        "siem_azure_client_id": getattr(settings, "siem_azure_client_id", "") or "",
        "siem_azure_client_secret_set": bool(getattr(settings, "siem_azure_client_secret", "")),
        "wazuh_base_url": getattr(settings, "wazuh_base_url", "") or "",
        "wazuh_user": getattr(settings, "wazuh_user", "") or "",
        "wazuh_password_set": bool(getattr(settings, "wazuh_password", "")),
        "wazuh_verify_ssl": bool(getattr(settings, "wazuh_verify_ssl", False)),
        "wazuh_sync_interval_sec": int(getattr(settings, "wazuh_sync_interval_sec", 1800) or 1800),
        "wazuh_indexer_url": getattr(settings, "wazuh_indexer_url", "") or "",
        "wazuh_indexer_user": getattr(settings, "wazuh_indexer_user", "") or "",
        "wazuh_indexer_password_set": bool(getattr(settings, "wazuh_indexer_password", "")),
        "openaudit_base_url": getattr(settings, "openaudit_base_url", "") or "",
        "openaudit_user": getattr(settings, "openaudit_user", "") or "",
        "openaudit_password_set": bool(getattr(settings, "openaudit_password", "")),
        "openaudit_api_prefix": getattr(settings, "openaudit_api_prefix", "") or "/open-audit/index.php",
        "openaudit_verify_ssl": bool(getattr(settings, "openaudit_verify_ssl", False)),
        "openaudit_sync_interval_sec": int(getattr(settings, "openaudit_sync_interval_sec", 3600) or 3600),
        "hardeningkitty_module_path": getattr(settings, "hardeningkitty_module_path", "") or "",
        "hardeningkitty_list": getattr(settings, "hardeningkitty_list", "") or "",
        "sonarqube_base_url": getattr(settings, "sonarqube_base_url", "") or "",
        "sonarqube_token_set": bool(getattr(settings, "sonarqube_token", "")),
        "sonarqube_project_key": getattr(settings, "sonarqube_project_key", "") or "",
        "sonarqube_verify_ssl": bool(getattr(settings, "sonarqube_verify_ssl", True)),
        "sonarqube_sync_interval_sec": int(getattr(settings, "sonarqube_sync_interval_sec", 3600) or 3600),
        "sonarqube_issue_types": getattr(settings, "sonarqube_issue_types", "") or "VULNERABILITY,SECURITY_HOTSPOT,BUG",
        "thehive_base_url": getattr(settings, "thehive_base_url", "") or "",
        "thehive_api_key_set": bool(getattr(settings, "thehive_api_key", "")),
        "thehive_verify_ssl": bool(getattr(settings, "thehive_verify_ssl", False)),
        "aws_region": getattr(settings, "aws_region", "") or "us-east-1",
        "aws_access_key_id_set": bool(getattr(settings, "aws_access_key_id", "")),
        "aws_secret_access_key_set": bool(getattr(settings, "aws_secret_access_key", "")),
        "azure_tenant_id": getattr(settings, "azure_tenant_id", "") or "",
        "azure_client_id": getattr(settings, "azure_client_id", "") or "",
        "azure_client_secret_set": bool(getattr(settings, "azure_client_secret", "")),
        "azure_subscription_id": getattr(settings, "azure_subscription_id", "") or "",
        "gcp_project_id": getattr(settings, "gcp_project_id", "") or "",
        "gcp_service_account_json": getattr(settings, "gcp_service_account_json", "") or "",
        "slack_webhook_url_set": bool(getattr(settings, "slack_webhook_url", "")),
        "teams_webhook_url_set": bool(getattr(settings, "teams_webhook_url", "")),
        "servicenow_instance_url": getattr(settings, "servicenow_instance_url", "") or "",
        "servicenow_username": getattr(settings, "servicenow_username", "") or "",
        "servicenow_password_set": bool(getattr(settings, "servicenow_password", "")),
        "smtp_host": getattr(settings, "smtp_host", "") or "",
        "smtp_port": int(getattr(settings, "smtp_port", 587) or 587),
        "smtp_username": getattr(settings, "smtp_username", "") or "",
        "smtp_from": getattr(settings, "smtp_from", "") or "securaiq@localhost",
        "smtp_use_tls": bool(getattr(settings, "smtp_use_tls", True)),
        "smtp_password_set": bool(getattr(settings, "smtp_password", "")),
        "sophos_client_id": getattr(settings, "sophos_client_id", "") or "",
        "sophos_client_secret_set": bool(getattr(settings, "sophos_client_secret", "")),
        "crowdstrike_client_id": getattr(settings, "crowdstrike_client_id", "") or "",
        "crowdstrike_client_secret_set": bool(getattr(settings, "crowdstrike_client_secret", "")),
        "crowdstrike_base_url": getattr(settings, "crowdstrike_base_url", "") or "https://api.crowdstrike.com",
        "sentinelone_base_url": getattr(settings, "sentinelone_base_url", "") or "",
        "sentinelone_api_token_set": bool(getattr(settings, "sentinelone_api_token", "")),
        "defender_tenant_id": getattr(settings, "defender_tenant_id", "") or "",
        "defender_client_id": getattr(settings, "defender_client_id", "") or "",
        "defender_client_secret_set": bool(getattr(settings, "defender_client_secret", "")),
        "defender_hunting_api": getattr(settings, "defender_hunting_api", "auto") or "auto",
        "ssh_patch_enabled": bool(getattr(settings, "ssh_patch_enabled", False)),
        "ssh_patch_user": getattr(settings, "ssh_patch_user", "") or "root",
        "ssh_patch_key_path": getattr(settings, "ssh_patch_key_path", "") or "",
        "ssh_patch_max_hosts": int(getattr(settings, "ssh_patch_max_hosts", 15) or 15),
        "software_sync_auto_enabled": bool(getattr(settings, "software_sync_auto_enabled", True)),
        "software_sync_interval_sec": int(getattr(settings, "software_sync_interval_sec", 3600) or 3600),
    }
    # Defense-in-depth: never allow raw secret keys in the payload
    forbidden = {
        "hf_token",
        "openai_compat_api_key",
        "hermes_api_key",
        "hermes_session_key",
        "api_key",
        "token",
        "password",
    }
    for key in list(payload):
        if key.lower() in forbidden or (
            is_secret_field(key) and not key.endswith("_set") and not key.endswith("_masked")
        ):
            payload.pop(key, None)
    return payload


# Keys that may be written from the Settings UI (never echo secrets back).
_WRITABLE: dict[str, tuple[str, type]] = {
    "openai_compat_base_url": ("OPENAI_COMPAT_BASE_URL", str),
    "openai_compat_model": ("OPENAI_COMPAT_MODEL", str),
    "openai_compat_api_key": ("OPENAI_COMPAT_API_KEY", str),
    "hermes_base_url": ("HERMES_BASE_URL", str),
    "hermes_model": ("HERMES_MODEL", str),
    "hermes_api_key": ("HERMES_API_KEY", str),
    "hermes_session_key": ("HERMES_SESSION_KEY", str),
    "hermes_show_tool_progress": ("HERMES_SHOW_TOOL_PROGRESS", bool),
    "hf_model": ("HF_MODEL", str),
    "hf_token": ("HF_TOKEN", str),
    "huggingface_api_model": ("HUGGINGFACE_API_MODEL", str),
    "unsloth_model": ("UNSLOTH_MODEL", str),
    "unsloth_adapter_dir": ("UNSLOTH_ADAPTER_DIR", str),
    "unsloth_max_seq_length": ("UNSLOTH_MAX_SEQ_LENGTH", int),
    "unsloth_load_in_4bit": ("UNSLOTH_LOAD_IN_4BIT", bool),
    "ollama_base_url": ("OLLAMA_BASE_URL", str),
    "ollama_model": ("OLLAMA_MODEL", str),
    "web_search_enabled": ("WEB_SEARCH_ENABLED", bool),
    "web_search_max_results": ("WEB_SEARCH_MAX_RESULTS", int),
    "web_search_timeout_sec": ("WEB_SEARCH_TIMEOUT_SEC", float),
    "searxng_url": ("SEARXNG_URL", str),
    "net_assess_enabled": ("NET_ASSESS_ENABLED", bool),
    "net_assess_use_nmap": ("NET_ASSESS_USE_NMAP", bool),
    "local_tools_enabled": ("LOCAL_TOOLS_ENABLED", bool),
    "local_tools_auto": ("LOCAL_TOOLS_AUTO", bool),
    "local_tools_allow_heavy": ("LOCAL_TOOLS_ALLOW_HEAVY", bool),
    "jira_base_url": ("JIRA_BASE_URL", str),
    "jira_email": ("JIRA_EMAIL", str),
    "jira_api_token": ("JIRA_API_TOKEN", str),
    "jira_project_key": ("JIRA_PROJECT_KEY", str),
    "router_enabled": ("ROUTER_ENABLED", bool),
    "openai_api_key": ("OPENAI_API_KEY", str),
    "openai_model": ("OPENAI_MODEL", str),
    "openrouter_api_key": ("OPENROUTER_API_KEY", str),
    "openrouter_model": ("OPENROUTER_MODEL", str),
    "groq_api_key": ("GROQ_API_KEY", str),
    "groq_model": ("GROQ_MODEL", str),
    "together_api_key": ("TOGETHER_API_KEY", str),
    "together_model": ("TOGETHER_MODEL", str),
    "fireworks_api_key": ("FIREWORKS_API_KEY", str),
    "fireworks_model": ("FIREWORKS_MODEL", str),
    "ollama_coder_model": ("OLLAMA_CODER_MODEL", str),
    "abuseipdb_api_key": ("ABUSEIPDB_API_KEY", str),
    "virustotal_api_key": ("VIRUSTOTAL_API_KEY", str),
    "shodan_api_key": ("SHODAN_API_KEY", str),
    "otx_api_key": ("OTX_API_KEY", str),
    "urlscan_api_key": ("URLSCAN_API_KEY", str),
    "hibp_api_key": ("HIBP_API_KEY", str),
    "greynoise_api_key": ("GREYNOISE_API_KEY", str),
    "pulsedive_api_key": ("PULSEDIVE_API_KEY", str),
    "malwarebazaar_api_key": ("MALWAREBAZAAR_API_KEY", str),
    "emailrep_api_key": ("EMAILREP_API_KEY", str),
    "urlhaus_api_key": ("URLHAUS_API_KEY", str),
    "github_webhook_secret": ("GITHUB_WEBHOOK_SECRET", str),
    "gitlab_webhook_secret": ("GITLAB_WEBHOOK_SECRET", str),
    "taxii_api_root": ("TAXII_API_ROOT", str),
    "taxii_collection_id": ("TAXII_COLLECTION_ID", str),
    "taxii_username": ("TAXII_USERNAME", str),
    "taxii_password": ("TAXII_PASSWORD", str),
    "oidc_enabled": ("OIDC_ENABLED", bool),
    "oidc_issuer": ("OIDC_ISSUER", str),
    "oidc_client_id": ("OIDC_CLIENT_ID", str),
    "oidc_client_secret": ("OIDC_CLIENT_SECRET", str),
    "oidc_redirect_uri": ("OIDC_REDIRECT_URI", str),
    "oidc_scopes": ("OIDC_SCOPES", str),
    "scim_enabled": ("SCIM_ENABLED", bool),
    "scim_token": ("SCIM_TOKEN", str),
    "mfa_required_for_admin": ("MFA_REQUIRED_FOR_ADMIN", bool),
    "database_url": ("DATABASE_URL", str),
    "redis_url": ("REDIS_URL", str),
    "redis_sentinel_hosts": ("REDIS_SENTINEL_HOSTS", str),
    "redis_sentinel_master": ("REDIS_SENTINEL_MASTER", str),
    "redis_sentinel_password": ("REDIS_SENTINEL_PASSWORD", str),
    "redis_stream_key": ("REDIS_STREAM_KEY", str),
    "redis_stream_maxlen": ("REDIS_STREAM_MAXLEN", int),
    "redis_stream_backpressure_len": ("REDIS_STREAM_BACKPRESSURE_LEN", int),
    "redis_stream_dlq_key": ("REDIS_STREAM_DLQ_KEY", str),
    "redis_stream_max_deliveries": ("REDIS_STREAM_MAX_DELIVERIES", int),
    "redis_stream_claim_idle_ms": ("REDIS_STREAM_CLAIM_IDLE_MS", int),
    "realtime_replay_buffer": ("REALTIME_REPLAY_BUFFER", int),
    "realtime_streams_fanout": ("REALTIME_STREAMS_FANOUT", bool),
    "event_idempotency_prune_days": ("EVENT_IDEMPOTENCY_PRUNE_DAYS", int),
    "evidence_observed_ttl_sec": ("EVIDENCE_OBSERVED_TTL_SEC", int),
    "prefect_enabled": ("PREFECT_ENABLED", bool),
    "prefect_api_url": ("PREFECT_API_URL", str),
    "siem_forward_enabled": ("SIEM_FORWARD_ENABLED", bool),
    "siem_forward_url": ("SIEM_FORWARD_URL", str),
    "siem_hec_token": ("SIEM_HEC_TOKEN", str),
    "siem_syslog_host": ("SIEM_SYSLOG_HOST", str),
    "siem_syslog_port": ("SIEM_SYSLOG_PORT", int),
    "siem_azure_sentinel_enabled": ("SIEM_AZURE_SENTINEL_ENABLED", bool),
    "siem_azure_dce_url": ("SIEM_AZURE_DCE_URL", str),
    "siem_azure_dcr_immutable_id": ("SIEM_AZURE_DCR_IMMUTABLE_ID", str),
    "siem_azure_stream_name": ("SIEM_AZURE_STREAM_NAME", str),
    "siem_azure_tenant_id": ("SIEM_AZURE_TENANT_ID", str),
    "siem_azure_client_id": ("SIEM_AZURE_CLIENT_ID", str),
    "siem_azure_client_secret": ("SIEM_AZURE_CLIENT_SECRET", str),
    "wazuh_base_url": ("WAZUH_BASE_URL", str),
    "wazuh_user": ("WAZUH_USER", str),
    "wazuh_password": ("WAZUH_PASSWORD", str),
    "wazuh_verify_ssl": ("WAZUH_VERIFY_SSL", bool),
    "wazuh_sync_interval_sec": ("WAZUH_SYNC_INTERVAL_SEC", int),
    "wazuh_indexer_url": ("WAZUH_INDEXER_URL", str),
    "wazuh_indexer_user": ("WAZUH_INDEXER_USER", str),
    "wazuh_indexer_password": ("WAZUH_INDEXER_PASSWORD", str),
    "openaudit_base_url": ("OPENAUDIT_BASE_URL", str),
    "openaudit_user": ("OPENAUDIT_USER", str),
    "openaudit_password": ("OPENAUDIT_PASSWORD", str),
    "openaudit_api_prefix": ("OPENAUDIT_API_PREFIX", str),
    "openaudit_verify_ssl": ("OPENAUDIT_VERIFY_SSL", bool),
    "openaudit_sync_interval_sec": ("OPENAUDIT_SYNC_INTERVAL_SEC", int),
    "hardeningkitty_module_path": ("HARDENINGKITTY_MODULE_PATH", str),
    "hardeningkitty_list": ("HARDENINGKITTY_LIST", str),
    "sonarqube_base_url": ("SONARQUBE_BASE_URL", str),
    "sonarqube_token": ("SONARQUBE_TOKEN", str),
    "sonarqube_project_key": ("SONARQUBE_PROJECT_KEY", str),
    "sonarqube_verify_ssl": ("SONARQUBE_VERIFY_SSL", bool),
    "sonarqube_sync_interval_sec": ("SONARQUBE_SYNC_INTERVAL_SEC", int),
    "sonarqube_issue_types": ("SONARQUBE_ISSUE_TYPES", str),
    "thehive_base_url": ("THEHIVE_BASE_URL", str),
    "thehive_api_key": ("THEHIVE_API_KEY", str),
    "thehive_verify_ssl": ("THEHIVE_VERIFY_SSL", bool),
    "aws_access_key_id": ("AWS_ACCESS_KEY_ID", str),
    "aws_secret_access_key": ("AWS_SECRET_ACCESS_KEY", str),
    "aws_region": ("AWS_REGION", str),
    "azure_tenant_id": ("AZURE_TENANT_ID", str),
    "azure_client_id": ("AZURE_CLIENT_ID", str),
    "azure_client_secret": ("AZURE_CLIENT_SECRET", str),
    "azure_subscription_id": ("AZURE_SUBSCRIPTION_ID", str),
    "gcp_project_id": ("GCP_PROJECT_ID", str),
    "gcp_service_account_json": ("GCP_SERVICE_ACCOUNT_JSON", str),
    "slack_webhook_url": ("SLACK_WEBHOOK_URL", str),
    "teams_webhook_url": ("TEAMS_WEBHOOK_URL", str),
    "servicenow_instance_url": ("SERVICENOW_INSTANCE_URL", str),
    "servicenow_username": ("SERVICENOW_USERNAME", str),
    "servicenow_password": ("SERVICENOW_PASSWORD", str),
    "smtp_host": ("SMTP_HOST", str),
    "smtp_port": ("SMTP_PORT", int),
    "smtp_username": ("SMTP_USERNAME", str),
    "smtp_password": ("SMTP_PASSWORD", str),
    "smtp_from": ("SMTP_FROM", str),
    "smtp_use_tls": ("SMTP_USE_TLS", bool),
    "sophos_client_id": ("SOPHOS_CLIENT_ID", str),
    "sophos_client_secret": ("SOPHOS_CLIENT_SECRET", str),
    "crowdstrike_client_id": ("CROWDSTRIKE_CLIENT_ID", str),
    "crowdstrike_client_secret": ("CROWDSTRIKE_CLIENT_SECRET", str),
    "crowdstrike_base_url": ("CROWDSTRIKE_BASE_URL", str),
    "sentinelone_api_token": ("SENTINELONE_API_TOKEN", str),
    "sentinelone_base_url": ("SENTINELONE_BASE_URL", str),
    "defender_tenant_id": ("DEFENDER_TENANT_ID", str),
    "defender_client_id": ("DEFENDER_CLIENT_ID", str),
    "defender_client_secret": ("DEFENDER_CLIENT_SECRET", str),
    "defender_hunting_api": ("DEFENDER_HUNTING_API", str),
    "ssh_patch_enabled": ("SSH_PATCH_ENABLED", bool),
    "ssh_patch_user": ("SSH_PATCH_USER", str),
    "ssh_patch_key_path": ("SSH_PATCH_KEY_PATH", str),
    "ssh_patch_max_hosts": ("SSH_PATCH_MAX_HOSTS", int),
    "software_sync_auto_enabled": ("SOFTWARE_SYNC_AUTO_ENABLED", bool),
    "software_sync_interval_sec": ("SOFTWARE_SYNC_INTERVAL_SEC", int),
}


def apply_settings_patch(data: dict[str, Any]) -> dict[str, Any]:
    updated: list[str] = []
    for field, (env_key, typ) in _WRITABLE.items():
        if field not in data:
            continue
        raw = data[field]
        if raw is None:
            continue

        # Skip blank / placeholder secrets (UI empty = keep existing)
        if is_secret_field(field):
            if is_blank_or_placeholder(raw):
                continue

        if typ is bool:
            value = bool(raw) if not isinstance(raw, str) else raw.strip().lower() in {"1", "true", "yes", "on"}
            setattr(settings, field, value)
            update_env_value(env_key, "true" if value else "false")
        elif typ is int:
            value = int(raw)
            setattr(settings, field, value)
            update_env_value(env_key, str(value))
        elif typ is float:
            value = float(raw)
            setattr(settings, field, value)
            update_env_value(env_key, str(value))
        else:
            value = str(raw).strip()
            if field.endswith("_dir") or field.endswith("_path"):
                value = normalize_path(value) if value else value
            setattr(settings, field, value)
            update_env_value(env_key, value)
            # Keep process env in sync for HF hub clients
            if field == "hf_token":
                import os

                os.environ["HF_TOKEN"] = value
                os.environ["HUGGING_FACE_HUB_TOKEN"] = value
        updated.append(field)

    # Response only includes masked public settings — never raw secrets
    return {"updated": updated, "settings": public_settings()}
